export const AppRoutes = {
  splash: '/splash',
  login: '/login',
  register: '/register',
  roleHome: '/home',
  home: '/(tabs)',
  driverHome: '/driver-home',
  driverScanning: '/driver-scanning',
  driverFound: '/driver-found',
  driverMatch: '/driver-match',
  selectRide: '/select-ride',
  booking: '/booking',
  payment: '/payment',
  paymentProcessing: '/payment-processing',
  paymentResult: '/payment-result',
  driverSearching: '/driver-searching',
  tripLive: '/trip-live',
  tripSummary: '/trip-summary',
  history: '/(tabs)/history',
  profile: '/(tabs)/profile',
} as const;
